name: FancyNpcs
description: $description
author: OliverHD
version: $version
main: de.oliver.fancynpcs.FancyNpcs
api-version: 1.19
folia-supported: true
load: POSTWORLD
softdepend:
  - PlaceholderAPI
  - PlotSquared
commands:
  FancyNpcs:
    permission: FancyNpcs.admin
  Npc:
    permission: FancyNpcs.npc
    description: Main command for the Npc plugin