name: FancyNpcs
main: de.oliver.fancynpcs.FancyNpcs
author: OliverHD
version: 1.1.5
api-version: 1.19
load: POSTWORLD
folia-supported: true
commands:
  FancyNpcs:
    permission: FancyNpcs.admin
  Npc:
    permission: FancyNpcs.admin
    description: Main command for the Npc plugin