name: NpcPlugin
main: de.oliver.NpcPlugin
author: OliverHD
version: 1.1.1
api-version: 1.20
load: POSTWORLD
commands:
  Npc:
    permission: NpcPlugin.admin
    description: Main command for the Npc plugin